scrape_configs:
  - job_name: 'otelcol'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'otelcol:8889' ]
      - targets: [ 'otelcol:8888' ]
  - job_name: myapp
    scrape_interval: 10s
    static_configs:
    - targets:
      - localhost:8001
