---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-promotion
  labels:
    app: svc-promotion
  namespace: svc-promotion
  annotations:
    configmap.reloader.stakater.com/reload: "env-svc-promotion"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svc-promotion
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: svc-promotion
    spec:
      imagePullSecrets:
      - name: registry
      containers:
      - name: svc-promotion-http
        image: git.edenfarm.id:5050/project-version3/erp-services/erp-promotion-service/uat:<VERSION>
        command: ["/app/service"]
        args: ["api"]
        ports:
          - name: http-port
            containerPort: 8001           
        imagePullPolicy: Always
        resources:
          requests:
            memory: 50Mi
            cpu: 15m
          limits:
            memory: 350Mi
            cpu: 200m
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: env-value
          mountPath: /app/env.toml
          subPath: env-svc-promotion.toml
          readOnly: true
      - name: svc-promotion-grpc
        image: git.edenfarm.id:5050/project-version3/erp-services/erp-promotion-service/uat:<VERSION>
        command: ["/app/service"]
        args: ["grpc"]
        ports:
          - name: grpc-port
            containerPort: 5001
        imagePullPolicy: Always
        resources:
          requests:
            memory: 50Mi
            cpu: 15m
          limits:
            memory: 350Mi
            cpu: 200m
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: env-value
          mountPath: /app/env.toml
          subPath: env-svc-promotion.toml
          readOnly: true
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Jakarta
            type: File
        - name: env-value
          configMap:
            name: env-svc-promotion
      tolerations:
      - key: instance_type
        value: on-spot
        effect: NoSchedule
        operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - devops
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - svc-promotion
            topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: svc-svc-promotion-http
  namespace: svc-promotion
  labels:
    app: svc-promotion-http
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-port
  selector:
    app: svc-promotion
---
apiVersion: v1
kind: Service
metadata:
  name: svc-svc-promotion-grpc
  namespace: svc-promotion
  labels:
    app: svc-promotion-grpc
spec:
  ports:
  - name: grpc
    protocol: TCP
    port: 5001
    targetPort: grpc-port
  selector:
    app: svc-promotion
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-svc-promotion
  namespace: svc-promotion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-promotion
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
