include:
  - project: 'project-version3/erp-infra/gitlab-ci'
    file:
      - 'sonarqube-check.yml'
      - 'cypress-test.yml'
      - 'cypress-push.yml'
      - 'build-image.yml'
      - 'deploy-image.yml'

stages:
  - test
  - reconfig
  - build
  - deploy

Cypress Test:
  script:
    - npm run e2e
