version: '3.1'
services:
  # MySQL
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_name
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  # MongoDB
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  # Redis
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  # Service Account
  erp-sa:
    image: git.edenfarm.id:5050/project-version3/erp-services/erp-account-service/dev:latest
    restart: always
    container_name: service-account
    volumes: 
      - svc_data:/apps
    environment:
      - name=value
    ports:
      - 8001:8001
    command: /bin/sh -c "/app/service"
    depends_on: 
      - mysql
      - grpc-sa

  # GRPC Service Account
  grpc-sa:
    image: git.edenfarm.id:5050/project-version3/erp-services/erp-account-service/dev:latest
    restart: always
    container_name: grpc-sa
    volumes: 
      - svc_data:/apps
    environment:
      - name=value
    ports:
      - 5001:5001
    command: /bin/sh -c "/app/service"
    depends_on: 
      - mysql

volumes:
  mysql_data:
  redis_data:
  mongo_data:
  svc_data: