---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mob-courier
  labels:
    app: mob-courier
  namespace: mob-courier
  annotations:
    configmap.reloader.stakater.com/reload: "env-mob-courier"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mob-courier
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mob-courier
    spec:
      imagePullSecrets:
      - name: registry
      containers:
      - name: mob-courier-http
        image: git.edenfarm.id:5050/project-version3/erp-services/erp-courier-mobile-service/uat:<VERSION>
        command: ["/app/service"]
        args: ["api"]
        ports:
          - name: http-port
            containerPort: 8001
        imagePullPolicy: Always
        resources:
          requests:
            memory: 50Mi
            cpu: 15m
          limits:
            memory: 350Mi
            cpu: 200m
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: env-value
          mountPath: /app/env.toml
          subPath: env-mob-courier.toml
          readOnly: true
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Jakarta
            type: File
        - name: env-value
          configMap:
            name: env-mob-courier
      tolerations:
      - key: instance_type
        value: service
        effect: NoSchedule
        operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - devops
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mob-courier
            topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mob-courier-http
  namespace: mob-courier
  labels:
    app: mob-courier-http
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-port
  selector:
    app: mob-courier
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-mob-courier
  namespace: mob-courier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mob-courier
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
