// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entity "git.edenfarm.id/project-version2/api/src/sales/sales_assignment/unit_test/entity"
	mock "github.com/stretchr/testify/mock"
)

// SubmissionDetailRepository is an autogenerated mock type for the SubmissionDetailRepository type
type SubmissionDetailRepository struct {
	mock.Mock
}

// CheckSubmissionDetail provides a mock function with given fields: id
func (_m *SubmissionDetailRepository) CheckSubmissionDetail(id int8) (*entity.SubmissionDetail, error) {
	ret := _m.Called(id)

	var r0 *entity.SubmissionDetail
	if rf, ok := ret.Get(0).(func(int8) *entity.SubmissionDetail); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SubmissionDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int8) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
